### ISSUE TITLE
Docker Compose Support (with help)

### ISSUE THREAD

**Issue by SelfhostedPro** [leonitousconforti/the-moby-effect#281]
### What is the problem this feature would solve?

Hey, I am the author of https://github.com/Selfhostedpro/Yacht and I’m interested in seeing if this would be a good alternative to dockerode for me. 

So far it looks very promising. I also struggled with the docker compose implementation (currently I’m basically just calling it with a child process). 

### What is the feature you are proposing to solve the problem?

I came across some docs on how docker plugins work here: https://docs.docker.com/engine/extend/plugin_api/#plugin-discovery

It looks like each one should expose an API that’s callable. I’ll dig in a bit more but thought it might provide some insight into building out that functionality. 

https://github.com/docker/compose/blob/main/pkg/api/api.go

**Comment by leonitousconforti** [comment]
Hey there.

I've considered docker compose support in the past, and the only reason I never implemented it is because it wasn't something I directly needed myself. I would consider it again though.

Could you share more about your use case and the problem you want to solve? It would help me determine exactly what I need to implement to get a POC to you as soon as possible. Like do you just need `docker compose up` and `docker compose down` as a bare minimum for now?

**Comment by SelfhostedPro** [comment]
Hey, this is how I’m currently using it:
https://github.com/SelfhostedPro/yacht-nuxt/blob/2a362ec09cc99048d3386670d421b0dace63a439/server/utils/projects/actions.ts#L67

https://github.com/SelfhostedPro/yacht-nuxt/blob/main/server/api/projects/action.post.ts

Just simple commands currently.  It’d be nice to get some of the more advanced ones together (like config/logs/etc)

It seems like it missing a well defined API is a common problem with unofficial SDKs: https://github.com/fussybeaver/bollard/issues/239

when I get a chance to dig in a bit more I’ll see if I can find some way to be able to use it.

**Comment by SelfhostedPro** [comment]
Also, I’m aware it’s built on effect. I don’t have previous experience but I’m a quick learner. 

Overall I’m utilizing most of the features in my project but this looks like a much more ergonomic library to use.

**Comment by leonitousconforti** [comment]
I've identified a path that I am going to move forward with, you can track my progress on #282.

**Comment by SelfhostedPro** [comment]
Nice, glad you were able to sort something out. I don’t know why the docker compose peeps keep their stuff so locked down. Thanks for revisiting!

**Comment by SelfhostedPro** [comment]
Also, I was wondering if you had any resources on running things without relying on Effect-TS? Would remove some of the barrier of entry for me to test things out without having to rewrite my entire project.

**Comment by leonitousconforti** [comment]
> Also, I was wondering if you had any resources on running things without relying on Effect-TS? Would remove some of the barrier of entry for me to test things out without having to rewrite my entire project.

Noting at the moment. Right now, everything says in effect land. I do not plan on adding anything in this library that would return a promise or a sync function instead of an effect (although I might be convinced if that is a deal breaker for you). If I were to do so, I think some features are incapable with that model - specifically some of the demuxing but I will have to check.

You could get away with just using `Effect.runPromise` or `Effect.runSync` at any of the boundaries and it should be fine though. I will add some examples for how to use `Effect.runPromise` if that would help

**Comment by leonitousconforti** [comment]
In any of the current examples, anywhere is says `NodeRuntime.runMain` (like [here](https://github.com/leonitousconforti/the-moby-effect/blob/e602e74e230fe971040b4c0d90e673539c5eb9f0/examples/build-image.ts#L70-L71)) you can replace that with `Effect.runPromise` and get a promise instead.

**Comment by leonitousconforti** [comment]
Very basic docker compose support has been implemented, see [this](https://github.com/leonitousconforti/the-moby-effect/blob/main/examples/docker-compose.ts) example. Will publish a release shortly.

If this is something you are still considering, then you can leave this issue open and I will keep adding more docker compose commands and all the flags. If Effect is proving too high of a barrier to entry, then please close the issue so I know not to keep dedicating time to this 🙂

**Comment by SelfhostedPro** [comment]
The examples are great, thanks! I’ll be testing it out over the next week or so and let you know how it goes.

**Comment by leonitousconforti** [comment]
If you need any help with Effect or if you want more synchronous communication you can find me in the [effect discord](https://discord.gg/effect-ts) as @leonitous

**Comment by leonitousconforti** [comment]
And although they weren't included in the example, `docker compose build` and `docker compose kill` have already been implemented.

**Comment by leonitousconforti** [comment]
I decided to implement some very very basic `promise` and `callback` based clients in #283. Not sure if this will ever get merged as I am still trying to figure out where it fits with everything else and I'm not sure that I want to maintain it. If it does get merged, it won't look much different than it does right now. I don't plan on adding any documentation from the `effect` docker engine to the methods in these clients, because I don't want to maintain it in both these places and in the base `effect` docker engine. You can certainly just copy+paste these clients into your application though before it gets merged (you will want to comment out the `start` method until that gets merged)

**Comment by leonitousconforti** [comment]
I ended up merging the callbacks+promises clients into main and added some examples to https://github.com/leonitousconforti/the-moby-effect/tree/main/examples

I know there is still more work to do on the docker compose client and adding more examples, but I am going to close this issue now because I feel like the initial request (a base docker compose client) has been implemented successfully.

Feel free to open new issues for other ideas / problems / help
